### ISSUE TITLE
T-rex 3.04 with Mellanox ConnectX-6 and dummy port shows errors instead of stats while sending traffic

### ISSUE THREAD

**Issue by norg** [cisco-system-traffic-generator/trex-core#1101]
While I have some T-rex setups running with Intel XL710 to achieve 40G with one port I struggle with a 100G setup based on Mellanox ConnectX-6 cards.

So far OFED installation worked, T-Rex setup as well and I can even see the traffic on the DUT but the report from T-rex shows errors instead of the rate, which I was used to from the setup with Intel NICS and DPDK.

T-Rex output:
```
Per port stats table
      ports |               0
 -----------------------------------------------------------------------------------------
   opackets |               0
     obytes |               0
   ipackets |               0
     ibytes |               0
    ierrors |       446702141
    oerrors |               0
      Tx Bw |       0.00  bps

-Global stats enabled
 Cpu Utilization : 3.2  %  0.0 Gb/core
 Platform_factor : 1.0
 Total-Tx        :       0.00  bps
 Total-Rx        :       0.00  bps
 Total-PPS       :       0.00  pps
 Total-CPS       :      27.00 Kcps

 Expected-PPS    :       1.20 Mpps
 Expected-CPS    :      18.04 Kcps
 Expected-BPS    :       4.24 Gbps

 Active-flows    :    15439  Clients :      255   Socket-util : 0.0961 %
 Open-flows      :   107208  Servers :    65535   Socket :    15439 Socket/Clients :  60.5
 drop-rate       :       0.00  bps
 current time    : 5.2 sec
 test duration   : 3594.8 sec
```
Runcommand:
```
/t-rex-64 -f cap2/sfr.yaml -p -c 4 -m 8 --cfg /etc/trex_cfg.yaml
```
I use `-p` to have the full flow received by the single port of the DUT (it's the Suricata IDS so I just need passive traffic forwarding towards it).

The `/etc/trex_cfg.yaml` looks like this:

```
### Config file generated by dpdk_setup_ports.py ###

- version: 2
  interfaces: ['82:00.1', 'dummy']
  port_info:
      - dest_mac: 94:6d:ae:c2:8d:11
        src_mac:  94:6d:ae:ef:b0:f9
      - dest_mac: 94:6d:ae:c2:8d:10
        src_mac:  94:6d:ae:ef:b0:f8

  platform:
      master_thread_id: 0
      latency_thread_id: 2
      dual_if:
        - socket: 1
          threads: [1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63]
```

While `82:00.1` is the port of the Mellanox NIC on the machine doing the traffic replay and the first destination mac being the DUT. But even if I remove the port info section it still shows those errors.

This type of setup with the `-p` flag and also the `dummy` in the config works with the Intel setup where I see the traffic rate and all those stats (of course just for `opackets` and `obytes` while `ipackets` is 0).

Is this just an output issue? I would like to see the stats and especially traffic rate being sent so I can verify on the DUT side if the traffic rate is received.

Thanks
