### ISSUE TITLE
How to use multiple cores when replaying PCAP file data?

### ISSUE THREAD

**Issue by wly-13** [cisco-system-traffic-generator/trex-core#1151]
Hi team,
When I tried to use trex to load PCAP file and replay the packets data, I found that only one core is fully used even I specified `-c 10` in the command line. And the max TX rate is about 3Mpps. How can I use multiple cores to replay packets of PCAP file to get a higher TX rate? Do you have some suggestions on it? Thanks. 

Below is my environment and config.

- OS: Ubuntu22.04
- Trex version: v3.00
- python script:
```
pcap_file = os.path.abspath(pcap_file)
self.client.push_remote(pcap_filename=pcap_file,
                                       ports=self.port,
                                       ipg_usec=self.ipg_usec,
                                       count=1)  
self.client.wait_on_traffic(ports=[0, 1])
```
- Trex config:
```
platform:
    master_thread_id: 0
    latency_thread_id: 20
    dual_if:
        - socket: 0
            threads: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
```
