### ISSUE TITLE
Trex on AWS Centos - with latency turned on, not able to send as much packets thru

### ISSUE THREAD

**Issue by chrlai** [cisco-system-traffic-generator/trex-core#530]
Hi, 
We have installed TRex (v2.83) on AWS EC2 (c5n.9x) with 4 ports with the following config
```
stack: linux_based
  memory:
    dp_flows: 1048576 
  low_end: false
  port_bandwidth_gb: 20
  services_core: 35
  rx_desc: 8192
  port_info:
      - ip: xx.xx.xx.xx
        default_gw: xx.xx.xx.xx
      - ip: xx.xx.xx.xx
        default_gw: xx.xx.xx.xx

      - ip: xx.xx.xx.xx
        default_gw: xx.xx.xx.xx
      - ip: xx.xx.xx.xx
        default_gw: xx.xx.xx.xx

  platform:
      master_thread_id: 0 
      latency_thread_id: 1
      dual_if:
        - socket: 0
          threads: [2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]

        - socket: 0
          threads: [18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33]
```
Looks like we have plateaued at 2.4Mpps with 4 ports running, setting up like the following
```
port0 -> DUT ->port1
port1->DUT->port0
port2->DUT->port3
port3->DUT->port2
```

Running the server with `t-rex-64 -c 16 --queue-drop -i`

Each port profile is set up to send 650Kpps

Checking the CUP and Memory usage when running, all cores are only being utilized at 4% and less than 15% of memory being used.

Looks like we can only reach max ~ 600Kpps per port with Latency turned OFF.  (total ~2.4MPPs)
With Latency ON, we can only reach max ~350Kpps per port (total ~1.4Mpps)

Are there more in configurations that I can tune or have I mis-configured something?  Thank you very much in advance.
