### ISSUE TITLE
port_info for ipv6 

### ISSUE THREAD

**Issue by hesingh** [cisco-system-traffic-generator/trex-core#642]
This is the trex_cfg.yaml file for IPv4 which works with latest trex.  

How do I change `ip` and `default_gw` in yaml to use IPv6 addresses?

```
### Config file generated by dpdk_setup_ports.py ###

- version: 2
  interfaces: ['00:09.0', '00:0a.0']
  port_info:
      - ip: 10.10.1.2
        default_gw: 10.10.1.1
      - ip: 10.10.2.2
        default_gw: 10.10.2.1
  platform:
      master_thread_id: 0
      latency_thread_id: 1
      dual_if:
        - socket: 0
          threads: [2,3,4,5,6,7]
```
