### ISSUE TITLE
VMware vm, rhel 7.9, i40e SRIOV failing

### ISSUE THREAD

**Issue by davehouser1** [cisco-system-traffic-generator/trex-core#649]
**System:**
Vmware 6.7
rhel 7.9 virtual machine
i40e nic
SRIOV enabled
trex version 2.87

**Problem:**
when running Trex and trying to generate traffic, all traffic seems to error out and only "oerrors" increments on both interfaces.

**My config:**
```
# cat /etc/trex_cfg.yaml
### Config file generated by dpdk_setup_ports.py ###

- version: 2
  interfaces: ['13:00.0', '1b:00.0']
  port_info:
      - dest_mac: 00:50:56:bd:22:c3 # MAC OF LOOPBACK TO IT'S DUAL INTERFACE
        src_mac:  00:50:56:bd:e9:36
      - dest_mac: 00:50:56:bd:e9:36 # MAC OF LOOPBACK TO IT'S DUAL INTERFACE
        src_mac:  00:50:56:bd:22:c3

  platform:
      master_thread_id: 0
      latency_thread_id: 1
      dual_if:
        - socket: 0
          threads: [2,3,4,5,6,7]
```

**Driver info:**
```
[root@taxmd01-trex-rhel scripts]# lspci | grep -i Ethernet
0b:00.0 Ethernet controller: VMware VMXNET3 Ethernet Controller (rev 01)
13:00.0 Ethernet controller: Intel Corporation Ethernet Virtual Function 700 Series (rev 02)
1b:00.0 Ethernet controller: Intel Corporation Ethernet Virtual Function 700 Series (rev 02)
```

**Trouble shooting:**
- Tried installing latest driver for i40e directly to the VM
- Tried rebooting the system
- Tried using "./t-rex-64 -i" and using the trex-stateless-gui
- Tried using the command "./t-rex-64 -f cap2/dns.yaml -c 1 -m 1 -d 100"
- Tried using the command "./t-rex-64-dbug -f cap2/dns.yaml -c 1 -m 1 -d 100" (but did not seem do anything different from the above command)
- Tried regenerating my trex config

**Notes:**
- Here is the output before starting up trex, is any of this possibly the source of the problem?
```
# ./t-rex-64 -f cap2/dns.yaml -c 1 -m 1 -d 100
The ports are bound/configured.
Starting  TRex v2.87 please wait  ...
 set driver name net_i40e_vf
 driver capability  : TCP_UDP_OFFLOAD  TSO
 set dpdk queues mode to ONE_QUE
 Number of ports found: 2
zmq publisher at: tcp://*:4500
i40evf_disable_vlan_strip(): Failed to execute command of VIRTCHNL_OP_DISABLE_VLAN_STRIPPING
i40evf_config_promisc(): fail to execute command CONFIG_PROMISCUOUS_MODE
i40evf_config_promisc(): fail to execute command CONFIG_PROMISCUOUS_MODE
i40evf_disable_vlan_strip(): Failed to execute command of VIRTCHNL_OP_DISABLE_VLAN_STRIPPING
i40evf_config_promisc(): fail to execute command CONFIG_PROMISCUOUS_MODE
i40evf_config_promisc(): fail to execute command CONFIG_PROMISCUOUS_MODE
 wait 1 sec .
port : 0
```

Question:
- Really just looking for some type of log, to determine why I am getting "oerros" I tried looking though the ./t-rex-64 --help, but I don't see verbose output or log info related to the errors (only "--rpc-log")
