### ISSUE TITLE
Intel 810E NIC fails to register properly using software mode

### ISSUE THREAD

**Issue by itwasscience** [cisco-system-traffic-generator/trex-core#694]
T-Rex v2.89 is unable to use Intel 810E cards. I saw in the v2.88 patch notes that this should be supported in software mode. Does this require more than just the `--software` flag to function?

**Debugging:**
```
root@foo:/opt/trex/v2.89# ./dpdk_nic_bind.py --status

Network devices using DPDK-compatible driver
============================================
0000:5e:00.0 'Ethernet Controller E810-C for QSFP' drv=igb_uio unused=ice
0000:5e:00.1 'Ethernet Controller E810-C for QSFP' drv=igb_uio unused=ice

Network devices using kernel driver
===================================
0000:1c:00.0 'Ethernet Connection X722 for 10GBASE-T' if=eno1 drv=i40e unused=igb_uio *Active*
0000:1c:00.1 'Ethernet Connection X722 for 10GBASE-T' if=eno2 drv=i40e unused=igb_uio
0000:af:00.0 'BCM57508 NetXtreme-E 10Gb/25Gb/40Gb/50Gb/100Gb/200Gb Ethernet' if=ens1f0np0 drv=bnxt_en unused=igb_uio
0000:af:00.1 'BCM57508 NetXtreme-E 10Gb/25Gb/40Gb/50Gb/100Gb/200Gb Ethernet' if=ens1f1np1 drv=bnxt_en unused=igb_uio
```

```
# cat /etc/trex_cfg.yaml
### Config file generated by dpdk_setup_ports.py ###

- version: 2
  interfaces: ['0000:5e:00.0', '0000:5e:00.1']
  port_bandwidth_gb: 200
  port_info:
      - ip: 1.1.1.1
        default_gw: 2.2.2.2
      - ip: 2.2.2.2
        default_gw: 1.1.1.1

  platform:
      master_thread_id: 0
      latency_thread_id: 1
      dual_if:
        - socket: 1
          threads: [10,11,12,13,14,15,16,17,18,19,30,31,32,33,34,35,36,37,38,39]
```

Error message on start:
```
root@foo:/opt/trex/v2.89# ./t-rex-64 -i --software
Starting Scapy server..... Scapy server is started
The ports are bound/configured.
Starting  TRex v2.89 please wait  ...
 set driver name net_ice
 driver capability  : TCP_UDP_OFFLOAD  TSO
 set dpdk queues mode to ONE_QUE
 Number of ports found: 2
zmq publisher at: tcp://*:4500
ice_program_hw_rx_queue(): currently package doesn't support RXDID (22)
ice_rx_queue_start(): fail to program RX queue 0
ice_dev_start(): fail to start Rx queue 0
ice_program_hw_rx_queue(): currently package doesn't support RXDID (22)
ice_rx_queue_start(): fail to program RX queue 0
ice_dev_start(): fail to start Rx queue 0
ice_program_hw_rx_queue(): currently package doesn't support RXDID (22)
ice_rx_queue_start(): fail to program RX queue 0
ice_dev_start(): fail to start Rx queue 0
ice_program_hw_rx_queue(): currently package doesn't support RXDID (22)
ice_rx_queue_start(): fail to program RX queue 0
ice_dev_start(): fail to start Rx queue 0
ice_program_hw_rx_queue(): currently package doesn't support RXDID (22)
ice_rx_queue_start(): fail to program RX queue 0
ice_dev_start(): fail to start Rx queue 0
ice_program_hw_rx_queue(): currently package doesn't support RXDID (22)
ice_rx_queue_start(): fail to program RX queue 0
ice_dev_start(): fail to start Rx queue 0
ice_program_hw_rx_queue(): currently package doesn't support RXDID (22)
ice_rx_queue_start(): fail to program RX queue 0
ice_dev_start(): fail to start Rx queue 0
ice_program_hw_rx_queue(): currently package doesn't support RXDID (22)
ice_rx_queue_start(): fail to program RX queue 0
ice_dev_start(): fail to start Rx queue 0
ice_program_hw_rx_queue(): currently package doesn't support RXDID (22)
ice_rx_queue_start(): fail to program RX queue 0
ice_dev_start(): fail to start Rx queue 0
ice_program_hw_rx_queue(): currently package doesn't support RXDID (22)
ice_rx_queue_start(): fail to program RX queue 0
ice_dev_start(): fail to start Rx queue 0
EAL: Error - exiting with code: 1
  Cause: rte_eth_dev_start: err=-5, port=0
Killing Scapy server... Scapy server is killed
```
