### ISSUE TITLE
Cannot generic traffic in astf module

### ISSUE THREAD

**Issue by FireSpoonYZ** [cisco-system-traffic-generator/trex-core#781]
I'm trying to generic simple http traffic, so I just copy the command in the document.
```
./t-rex-64 -i --astf
```
And in another terminal
```
./trex-console -s 10.22.33.180
>start -f astf/http_simple.py -m 1000 -d 1000 -l 1000
```
It print [SUCCESS] in console, but I noticed that it doesn't work correctly. I have no idea what is wrong here.

```
Using 'python3' as Python interpeter


Connecting to RPC server on 10.22.33.180:4501                [SUCCESS]


Connecting to publisher server on 10.22.33.180:4500          [SUCCESS]


Acquiring ports [0, 1]:                                      [SUCCESS]


Server Info:

Server version:   v2.92 @ ASTF
Server mode:      Advanced Stateful
Server CPU:       1 x AMD EPYC 7542 32-Core Processor
Ports count:      2 x 10Gbps @ VMXNET3 Ethernet Controller

-=TRex Console v3.0=-

Type 'help' or '?' for supported actions

trex>start -f astf/http_simple.py -m 1000 -d 1000 -l 1000

Loading traffic at acquired ports.                           [SUCCESS]


Starting traffic.                                            [SUCCESS]

29.33 [ms]

```

```
-Per port stats table
      ports |               0 |               1
 -----------------------------------------------------------------------------------------
   opackets |          234752 |               0
     obytes |        18051900 |               0
   ipackets |              27 |              27
     ibytes |            1728 |            1728
    ierrors |               0 |               0
    oerrors |               0 |               0
      Tx Bw |       7.43 Mbps |       0.00  bps

-Global stats enabled
 Cpu Utilization : 3.5  %  0.4 Gb/core
 Platform_factor : 1.0
 Total-Tx        :       7.43 Mbps
 Total-Rx        :     706.39  bps
 Total-PPS       :      12.07 Kpps
 Total-CPS       :       2.77 Kcps

 Expected-PPS    :       0.00  pps
 Expected-CPS    :       0.00  cps
 Expected-L7-BPS :       0.00  bps

 Active-flows    :    13878  Clients :        0   Socket-util : 0.0000 %
 Open-flows      :    59545  Servers :        0   Socket :        0 Socket/Clients :  -nan
 drop-rate       :       7.43 Mbps
 current time    : 44.0 sec
 test duration   : 0.0 sec
```
There's 3 network interfaces on this machine, one for ssh with ip address 10.22.33.180, and two left was used for traffic generic.
Here is my config in /etc/trex_cfg.yml. 
```
- version: 2
  interfaces: ['0b:00.0', '13:00.0']
  port_info:
      - ip: 192.168.1.3
        default_gw: 192.168.1.1
      - ip: 192.168.1.81
        default_gw: 192.168.1.1

  platform:
      master_thread_id: 0
      latency_thread_id: 1
      dual_if:
        - socket: 0
          threads: [2,3]

```
