### ISSUE TITLE
ASTF multi instance broken - v2.84 to v2.97

### ISSUE THREAD

**Issue by bdollma** [cisco-system-traffic-generator/trex-core#862]
Running multiple instances with ASTF doesn't work with the official image starting from v2.84. 
In this version the new memory for DPDK was introduced.

## What is the last working version?

The last working version as described in the FAQ is version 2.83

The following parameters are required in the configuration file:

```yaml
  prefix: instance2
  zmq_pub_port: 4600
  zmq_rpc_port: 4601
  limit_memory: 4096
```

## Can I make it work in v2.84-v2.97 if I really want to?

Yes. You need to compile your own version of TRex however with the `--new-memory` flag.

1. Install the required library for NUMA, for example: `sudo yum install numactl-devel` or the relevant package in other distros.
2. `cd linux_dpdk`
3. `./b configure --new-memory`
4. `./b build`

You still need the flags in `trex_cfg.yaml` as described in the FAQ.

## What happens in the future?

- If you are using one NUMA (`socket` as named in `trex_cfg`) you can add the `new_memory: true` line the configuration file together with the `prefix` and other flags.
   ```yaml
  new_memory: true
  prefix: instance2
  zmq_pub_port: 4600
  zmq_rpc_port: 4601
  limit_memory: 4096
  ```
- If you are using multiple NUMAs you need to compile using the steps described before.
