### ISSUE TITLE
How to configure bond interface with lacp ?

### ISSUE THREAD

**Issue by wlooppy** [cisco-system-traffic-generator/trex-core#911]
i want  use bond interface  in v2.99, but trex not to start, here is the error and  trex_cfg.yaml, is there something wrong in the trex_cfg.yaml?

cat /etc/trex_cfg.yaml
- port_limit: 2
  version: 2
  limit_memory: 18432,18432
  #interfaces: ['da:00.0', "dummy"]
  interfaces: [ '--vdev=net_bonding0,mode=0,slave=1a:00.1,slave=da:00.0','dummy' ]
  port_bandwidth_gb: 10

./t-rex-64 -i --no-scapy-server -w 10
The ports are bound/configured.
Starting  TRex v2.99 please wait  ...
bond_ethdev_parse_slave_port_kvarg(125) - Invalid slave port value (1a:00.1) specified
bond_ethdev_configure(3745) - Failed to parse slave ports for bonded device net_bonding0
Port0 dev_configure = -1
 set driver name net_bonding
 driver capability  : SLRO
 set dpdk queues mode to ONE_QUE
 Number of ports found: 2 (dummy among them: 1)
zmq publisher at: tcp://*:4500
Requested TX offload MULTI_SEGS is not supported
Requested RX offload SCATTER is not supported

**Comment by wly-13** [comment]
hello, did you solve this problem?

**Comment by voodam** [comment]
Hello. If you need this only for sending traffic from pair of interfaces, you could do this without bond, see my setup example:

```
- version: 2
  interfaces: ['98:00.0', 'dummy', '98:00.1', 'dummy']
  port_info:
      - ip: 192.168.253.106 # Generator port 1
        default_gw: 192.168.253.107 # SUT port 2
      - ip: 192.168.253.116 # Dummy port, fake IPs
        default_gw: 192.168.253.117
      - ip: 192.168.254.106 # Generator port 2
        default_gw: 192.168.254.107 # SUT port 2
      - ip: 192.168.254.116 # Dummy port, fake IPs
        default_gw: 192.168.254.117

  platform:
      master_thread_id: 0
      latency_thread_id: 2
      dual_if:
        - socket: 1
          threads: [1,3,5,7]
        - socket: 1
          threads: [9,11,13,15]
```
