### ISSUE TITLE
Unable to start TRex: ixgbe_dev_start(): failure in ixgbe_dev_start(): -38

### ISSUE THREAD

**Issue by fernandolcx** [cisco-system-traffic-generator/trex-core#934]
First time testing TRex, I'm unable to start the server:
```
root@s1200-ubuntu2004:/home/lab/trex-v3.00# ./t-rex-64 -i -c 1
Starting Scapy server.... Scapy server is started
The ports are bound/configured.
Starting  TRex v3.00 please wait  ...
 set driver name net_ixgbe
 driver capability  : TCP_UDP_OFFLOAD  TSO  SLRO
 set dpdk queues mode to DROP_QUE_FILTER
 Number of ports found: 2
zmq publisher at: tcp://*:4500
ixgbe_dev_start(): failure in ixgbe_dev_start(): -38
ixgbe_dev_start(): failure in ixgbe_dev_start(): -38
ixgbe_dev_start(): failure in ixgbe_dev_start(): -38
ixgbe_dev_start(): failure in ixgbe_dev_start(): -38
ixgbe_dev_start(): failure in ixgbe_dev_start(): -38
ixgbe_dev_start(): failure in ixgbe_dev_start(): -38
ixgbe_dev_start(): failure in ixgbe_dev_start(): -38
ixgbe_dev_start(): failure in ixgbe_dev_start(): -38
ixgbe_dev_start(): failure in ixgbe_dev_start(): -38
ixgbe_dev_start(): failure in ixgbe_dev_start(): -38
EAL: Error - exiting with code: 1
  Cause: rte_eth_dev_start: err=-5, port=0
Killing Scapy server... Scapy server is killed
```

### My environment:
Motherboard: Intel S1200BTLR
CPU: Intel Xeon E3-1270 v2
NIC: Intel 82598EB 10-Gigabit AF

```
root@s1200-ubuntu2004:/home/lab/trex-v3.00# ./dpdk_setup_ports.py -s

Network devices using DPDK-compatible driver
============================================
0000:01:00.0 '82598EB 10-Gigabit AF Dual Port Network Connection' drv=uio_pci_generic unused=ixgbe,igb_uio,vfio-pci
0000:01:00.1 '82598EB 10-Gigabit AF Dual Port Network Connection' drv=uio_pci_generic unused=ixgbe,igb_uio,vfio-pci

Network devices using kernel driver
===================================
0000:00:19.0 '82579LM Gigabit Network Connection (Lewisville)' if=eno1 drv=e1000e unused=igb_uio,vfio-pci,uio_pci_generic
0000:04:00.0 '82576 Gigabit Network Connection' if=enp4s0f0 drv=igb unused=igb_uio,vfio-pci,uio_pci_generic
0000:04:00.1 '82576 Gigabit Network Connection' if=enp4s0f1 drv=igb unused=igb_uio,vfio-pci,uio_pci_generic
0000:06:00.0 '82576 Gigabit Network Connection' if=enp6s0f0 drv=igb unused=igb_uio,vfio-pci,uio_pci_generic
0000:06:00.1 '82576 Gigabit Network Connection' if=enp6s0f1 drv=igb unused=igb_uio,vfio-pci,uio_pci_generic
0000:09:00.0 '82574L Gigabit Network Connection' if=enp9s0 drv=e1000e unused=igb_uio,vfio-pci,uio_pci_generic *Active*

Other network devices
=====================
<none>
```

```yaml
root@s1200-ubuntu2004:/home/lab/trex-v3.00# cat /etc/trex_cfg.yaml
### Config file generated by dpdk_setup_ports.py ###

- version: 2
  interfaces: ['01:00.0', '01:00.1']
  port_info:
      - dest_mac: 00:1b:21:8d:a7:b6 # MAC OF LOOPBACK TO IT'S DUAL INTERFACE
        src_mac:  00:1b:21:8d:a7:b7
      - dest_mac: 00:1b:21:8d:a7:b7 # MAC OF LOOPBACK TO IT'S DUAL INTERFACE
        src_mac:  00:1b:21:8d:a7:b6

  platform:
      master_thread_id: 0
      latency_thread_id: 1
      dual_if:
        - socket: 0
          threads: [2,3]
```

**Comment by Manah7** [comment]
Same problem here with Intel `82598EB 10-Gigabit` too. This is a fresh DPDK / TRex install. No difficulty with DPDK in standard use (for example, `testpmd` works fine).

Config. file:
```
### Config file generated by dpdk_setup_ports.py ###

- version: 2
  interfaces: ['0000:04:00.0', '0000:04:00.1']
  port_info:
      - ip: 1.1.1.1
        default_gw: 2.2.2.2
      - ip: 2.2.2.2
        default_gw: 1.1.1.1

  platform:
      master_thread_id: 0
      latency_thread_id: 11
      dual_if:
        - socket: 0
          threads: [1,2,3,4,5,6,7,8,9,10]
```
`dpdk-devbind.py -s`:
```
Network devices using DPDK-compatible driver
============================================
0000:04:00.0 '82598EB 10-Gigabit AF Dual Port Network Connection 10f1' drv=vfio-pci unused=ixgbe
0000:04:00.1 '82598EB 10-Gigabit AF Dual Port Network Connection 10f1' drv=vfio-pci unused=ixgbe

Network devices using kernel driver
===================================
0000:01:00.0 'I350 Gigabit Network Connection 1521' if=eno1 drv=igb unused=vfio-pci *Active*
...
0000:05:00.0 '82598EB 10-Gigabit AF Dual Port Network Connection 10f1' if=enp5s0f0 drv=ixgbe unused=vfio-pci 
0000:05:00.1 '82598EB 10-Gigabit AF Dual Port Network Connection 10f1' if=enp5s0f1 drv=ixgbe unused=vfio-pci
```
Full logs on documentation example:
```
# ./t-rex-64 -f cap2/dns.yaml -d 10
Trying to bind to vfio-pci ...
/usr/bin/python3 dpdk_nic_bind.py --bind=vfio-pci 0000:04:00.0 0000:04:00.1 
The ports are bound/configured.
Starting  TRex v3.02 please wait  ... 
 set driver name net_ixgbe 
 driver capability  : TCP_UDP_OFFLOAD  TSO  SLRO 
 set dpdk queues mode to DROP_QUE_FILTER 
 Number of ports found: 2
zmq publisher at: tcp://*:4500
ixgbe_dev_start(): failure in ixgbe_dev_start(): -38
EAL: Error disabling MSI-X interrupts for fd 23
ixgbe_dev_start(): failure in ixgbe_dev_start(): -38
EAL: Error disabling MSI-X interrupts for fd 23
ixgbe_dev_start(): failure in ixgbe_dev_start(): -38
EAL: Error disabling MSI-X interrupts for fd 23
ixgbe_dev_start(): failure in ixgbe_dev_start(): -38
EAL: Error disabling MSI-X interrupts for fd 23
ixgbe_dev_start(): failure in ixgbe_dev_start(): -38
EAL: Error disabling MSI-X interrupts for fd 23
ixgbe_dev_start(): failure in ixgbe_dev_start(): -38
EAL: Error disabling MSI-X interrupts for fd 23
ixgbe_dev_start(): failure in ixgbe_dev_start(): -38
EAL: Error disabling MSI-X interrupts for fd 23
ixgbe_dev_start(): failure in ixgbe_dev_start(): -38
EAL: Error disabling MSI-X interrupts for fd 23
ixgbe_dev_start(): failure in ixgbe_dev_start(): -38
EAL: Error disabling MSI-X interrupts for fd 23
ixgbe_dev_start(): failure in ixgbe_dev_start(): -38
EAL: Error - exiting with code: 1
  Cause: rte_eth_dev_start: err=-5, port=0
```
Thanks for your help!
